#!/bin/sh

PREREQ=""

# Output pre-requisites
prereqs()
{
        echo "$PREREQ"
}

case $1 in
        prereqs)
                prereqs
                exit 0
                ;;
esac

mkdir -p "$DESTDIR/lib/firmware/qcom"
cp -r /lib/firmware/qcom/qcm6490 $DESTDIR/lib/firmware/qcom/
cp -r /lib/firmware/qcom/qcs6490 $DESTDIR/lib/firmware/qcom/

exit 0
